name: Deploy Vite Static Site to Render

on:
  push:
    branches:
      - cookie_final  # replace with your actual branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build the static site
        run: npm run build

      - name: Trigger Render Deploy Hook
        run: curl -X POST https://api.render.com/deploy/srv-d10ivv63jp1c7391ni30?key=qfE3m4SzytM